package domain;

/**
 * Códigos de erro de validação e processamento
 */
public enum Erro {
	CPF_INVALIDO,
	NOME_INVALIDO,
	DATA_INVALIDA,
	CLIENTE_MENOR_DE_IDADE,
	CPF_JA_EXISTENTE,
	LOGRADOURO_INVALIDO,
	NUMERO_INVALIDO,
	COMPLEMENTO_INVALIDO,
	BAIRRO_INVALIDO,
	CIDADE_INVALIDA,
	CEP_INVALIDO,
	UF_INVALIDA,
	DDD_INVALIDO,
	NUMERO_TEL_INVALIDO,
	ENDERECO_INVALIDO,
	TELEFONE_INVALIDO,
	ERRO_BD,
	CLIENTE_NAO_ENCONTRADO,
	PLACA_INVALIDA,
	MODELO_INVALIDO,
	ANO_FABRICACAO_INVALIDO,
	VALOR_DIARIA_INVALIDO,
	QUILOMETRAGEM_INVALIDA,
	VEICULO_JA_EXISTENTE,
	VEICULO_NAO_ENCONTRADO
}
